# Generated by Django 5.0.6 on 2026-07-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recording",
            name="video_file",
            field=models.FileField(
                blank=True, null=True, upload_to="recordings/videos/%Y/%m/%d/"
            ),
        ),
    ]
